name: Format Code CI

on:
    push:
        branches: ['develop']
jobs:
  test:
    runs-on: ["ubuntu-latest"]
    node-version: [16.x]
  
  steps:
    - uses: actions/checkout@v2

    - name: Use Node on ubuntu-latest machine
      uses: actions/setup-node@v1

    - name: Install Node Modules
      run: npm install

    - name: Format Code using Prettier
      run: npm run format