name: Format Code CI

on:
    push:
        branches: ['develop']
jobs:
    test:
        runs-on: ubuntu-latest
        node-version: [16.x]

    steps:
        - name: Checkout Code
        - uses: actions/checkout@v2

        - name: Install Nodejs
          uses: actions/setup-node@v2

        - name: Install Node Modules
          run: npm install

        - name: Format Code using Prettier
          run: npm run format
